# Generated by Django 4.0.1 on 2022-02-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_id', models.CharField(max_length=20)),
                ('author', models.TextField()),
            ],
        ),
    ]
