# Generated by Django 4.0.2 on 2022-02-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_stars',
            field=models.ManyToManyField(to='api.Star', verbose_name='list of stars'),
        ),
    ]
