# Generated by Django 4.0.2 on 2022-02-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_user_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
